In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [78]:
def rsrs(file, N, M, frequency):
    data = pd.read_csv(file)
    if frequency == "1h" :
        # calculate beta
        beta = [0]*len(data.time)
        for i in range(N, len(data.time)) :
            data_temp = data[i-N:i]
            low = np.array(data_temp['low']).reshape(-1,1)
            high = np.array(data_temp['high']).reshape(-1,1)
            reg = LinearRegression().fit(X=low, y=high)
            beta[i] = reg.coef_[0][0]
        # rsrs
        rsrs = [0]*len(data.time)
        for i in range(M+N,len(data.time)) :
            beta_temp = beta[i-N:i]
            mu = np.mean(beta_temp)
            std = np.std(beta_temp)
            rsrs[i] =(beta[i] - mu )/std
        rsrs = pd.DataFrame({'rsrs':rsrs},index = data.time)
        return(rsrs.iloc[N+M::])
    elif frequency == "daily" :
        n = int(data.shape[0]/7)
        data = data.iloc[[i*7 for i in range(n)],:] # daily
        # calculate beta
        beta = [0]*len(data.time)
        for i in range(N, len(data.time)) :
            data_temp = data[i-N:i]
            low = np.array(data_temp['low']).reshape(-1,1)
            high = np.array(data_temp['high']).reshape(-1,1)
            reg = LinearRegression().fit(X=low, y=high)
            beta[i] = reg.coef_[0][0]
        # rsrs
        rsrs = [0]*len(data.time)
        for i in range(M+N,len(data.time)) :
            beta_temp = beta[i-N:i]
            mu = np.mean(beta_temp)
            std = np.std(beta_temp)
            rsrs[i] =(beta[i] - mu )/std
        rsrs = pd.DataFrame({'rsrs':rsrs},index = data.time)
        return(rsrs.iloc[N+M::])

In [79]:
rsrs('/Users/guanjing/Desktop/SP_SPX, 1h.csv',50,300,"1h")

                               rsrs
time
2016-03-16T09:30:00-04:00 -1.645270
2016-03-16T10:30:00-04:00 -1.535269
2016-03-16T11:30:00-04:00 -1.519568
2016-03-16T12:30:00-04:00 -1.555847
2016-03-16T13:30:00-04:00 -1.444452
...                             ...
2022-04-14T11:30:00-04:00  2.052934
2022-04-14T12:30:00-04:00  2.087682
2022-04-14T13:30:00-04:00  2.154005
2022-04-14T14:30:00-04:00  2.100492
2022-04-14T15:30:00-04:00  2.189172

[10703 rows x 1 columns]

In [80]:
rsrs('/Users/guanjing/Desktop/SP_SPX, 1h.csv',50,300,"daily")

                               rsrs
time
2017-05-24T11:30:00-04:00 -1.272510
2017-05-25T11:30:00-04:00 -1.255818
2017-05-26T11:30:00-04:00 -1.012022
2017-05-30T11:30:00-04:00 -0.949995
2017-05-31T11:30:00-04:00 -0.909484
...                             ...
2022-04-08T09:30:00-04:00  0.304024
2022-04-11T09:30:00-04:00  0.242866
2022-04-12T09:30:00-04:00  0.269445
2022-04-13T09:30:00-04:00  0.222735
2022-04-14T09:30:00-04:00  0.101325

[1229 rows x 1 columns]